### PR TITLE
Fix typescript typings

### LINKED ISSUE #46: koaJwtSecret type declaration is incorrect
This is causing errors in my typeScript code.

### LINKED ISSUE #52: @types/express-jwt included in dependencies
The `@types/express-jwt` package is added as a dependency, instead of devDependency. This is pulling a number of `@types` packages into our production build that shouldn't be necessary.

### PR DESCRIPTION
**Pull request by fnberta**
The typescript typings are not really accurate at the moment. This fixes them. Note that jwt-express types should be listed in dependencies (as they are now) because we re-export a type from that package.

Incorporates #73, #69, #54.
Fixes #46, #28, #78, #75.

### CODE REVIEW

**Comment by tinaroh** [comment]
auth0, please merge this!

**Comment by AlexRex** [comment]
Please! Merge!

File: index.d.ts [hunk 1]
```diff
@@ -1,67 +1,97 @@
...
+    header: TokenHeader;
+  }
+
+  interface TokenHeader {
+    alg: string;
+    kid: string;
+  }
 
-    function koaJwtSecret(options: JwksRsa.Options): (name: string, scheme: string, options?: any) => void;
+  function hapiJwt2KeyAsync(options: HapiJwtOptions): (decodedToken: DecodedToken) => Promise<{ key: SigningKey }>;
```
Comment (igorsechyn) [inline index.d.ts]:
```
(decodedToken: DecodedToken) => Promise<{ key: SigningKey }>;
```
this is actually wrong. it does not return a promise of `SigningKey`, they `key` property is just a string with the value. See:
- https://github.com/auth0/node-jwks-rsa/blob/master/src/integrations/hapi.js#L25
- https://github.com/auth0/node-jwks-rsa/blob/master/src/integrations/hapi.js#L58

I wrote a test for verifying the typings here https://github.com/auth0/node-jwks-rsa/pull/98

Comment (fnberta) [reply index.d.ts]: Good catch, thanks! Fixed it.

File: package.json [hunk 2]
```diff
@@ -5,6 +5,7 @@
   "main": "lib/index.js",
   "types": "index.d.ts",
   "dependencies": {
+    "@types/express-jwt": "0.0.41",
```
Comment (luisrudge) [inline package.json]: this should be a dev dependency

Comment (denkristoffer) [reply package.json]: The TypeScript handbook recommends using `dependencies`, because otherwise consumers will have to install `@types/express-jwt` manually: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#dependencies

Comment (luisrudge) [reply package.json]: Thanks for the link!
